// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class BinMaster
{
    public int? Id { get; set; }

    public string Title { get; set; }

    public string Code { get; set; }
}