// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class EmployeeMaster
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string EmailId { get; set; }

    public string Phone { get; set; }

    public int? Age { get; set; }

    public int? Salary { get; set; }
}